name: "KiCad CI/CD"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'pcb/*.sch'
      - 'pcb/*.kicad_pcb'
      - 'pcb/*.kibot.yaml'
      - 'pcb/Makefile'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - 'pcb_prog/*.sch'
      - 'pcb_prog/*.kicad_pcb'
      - 'pcb_prog/*.kibot.yaml'
      - 'pcb_prog/Makefile'
      - '.github/workflows/kibot.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto:latest

    steps:
    - uses: actions/checkout@v3

    - name: Run ERC
      run: |
        make -C pcb erc
    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ERC_Output
        path: pcb/Fabrication

  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v3

    - name: Run DRC
      run: |
        make -C pcb drc
    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: DRC_Output
        path: pcb/Fabrication

  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto:latest
    needs: ERC

    steps:
    - uses: actions/checkout@v3

    - name: Run schematic stuff
      run: |
        make -C pcb sch_fab
    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: FabSch_Output
        path: |
          pcb/Fabrication/
          pcb/kibot_error.log
        if-no-files-found: warn

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto:latest
    needs: DRC

    steps:
    - uses: actions/checkout@v3

    - name: Run PCB stuff
      run: |
        make -C pcb pcb_fab
    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: FabPCB_Output
        path: |
          pcb/Fabrication/
          pcb/kibot_error.log
        if-no-files-found: warn
